<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="P04284" name="testCases.backend.api.TestB2BCreateAccountAPI" tests="2" failures="0" timestamp="2022-01-05T16:51:31 GMT" time="305.671" errors="1">
  <testcase name="testCreateNewB2BAccountBEGovernment" time="305.671" classname="testCases.backend.api.TestB2BCreateAccountAPI">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at microservices.backend.eir_order_management_backend.dao.OrderManagementDAO.getOrderStatus(OrderManagementDAO.java:371)
at microservices.backend.eir_order_management_backend.monitor.OrderManagementMonitor.waitForOrderToComplete(OrderManagementMonitor.java:22)
at microservices.backend.eir_order_management_backend.utility.B2BBackendAccountCreator.createAccountViaBE(B2BBackendAccountCreator.java:25)
at testCases.backend.api.TestB2BCreateAccountAPI.testCreateNewB2BAccountBEGovernment(TestB2BCreateAccountAPI.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testCreateNewB2BAccountBEGovernment -->
  <testcase name="testCreateNewB2BMultiLevelAccountBE" classname="testCases.backend.api.TestB2BCreateAccountAPI">
    <skipped/>
  </testcase> <!-- testCreateNewB2BMultiLevelAccountBE -->
</testsuite> <!-- testCases.backend.api.TestB2BCreateAccountAPI -->
