<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="7" hostname="P04284" name="testCases.middleware.aoc.test_cases.TestAoCSOAP" tests="8" failures="0" timestamp="2022-03-28T11:48:27 BST" time="6.251" errors="1">
  <testcase name="testAoCDD" time="0.000" classname="testCases.middleware.aoc.test_cases.TestAoCSOAP">
    <skipped/>
  </testcase> <!-- testAoCDD -->
  <testcase name="setUp" time="6.251" classname="testCases.middleware.aoc.test_cases.TestAoCSOAP">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at external_systems.mmw.MMWUtility.reprovisionEC20Subsriber(MMWUtility.java:423)
at testCases.middleware.aoc.test_cases.TestAoCSOAP.setUp(TestAoCSOAP.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase name="testAoCDD" time="0.000" classname="testCases.middleware.aoc.test_cases.TestAoCSOAP">
    <skipped/>
  </testcase> <!-- testAoCDD -->
  <testcase name="testAoCDD" time="0.000" classname="testCases.middleware.aoc.test_cases.TestAoCSOAP">
    <skipped/>
  </testcase> <!-- testAoCDD -->
  <testcase name="testAoCDD" time="0.000" classname="testCases.middleware.aoc.test_cases.TestAoCSOAP">
    <skipped/>
  </testcase> <!-- testAoCDD -->
  <testcase name="testAoCDD" time="0.000" classname="testCases.middleware.aoc.test_cases.TestAoCSOAP">
    <skipped/>
  </testcase> <!-- testAoCDD -->
  <testcase name="testAoCDD" time="0.000" classname="testCases.middleware.aoc.test_cases.TestAoCSOAP">
    <skipped/>
  </testcase> <!-- testAoCDD -->
  <testcase name="testAoCDD" time="0.000" classname="testCases.middleware.aoc.test_cases.TestAoCSOAP">
    <skipped/>
  </testcase> <!-- testAoCDD -->
</testsuite> <!-- testCases.middleware.aoc.test_cases.TestAoCSOAP -->
